CREATE DATABASE WEB1_CRUD;

USE WEB1_CRUD;

CREATE TABLE WCR_USER (
	USR_ID INT AUTO_INCREMENT,
    USR_NAME VARCHAR(120),
    USR_EMAIL VARCHAR(120),
    USR_CPF INT,
    USR_PASSWD VARCHAR(20),
    PRIMARY KEY(USR_ID)
);


CREATE TABLE WCR_BOLTS (
	BLT_ID INT AUTO_INCREMENT,
    BLT_BRAND VARCHAR(40),
	BLT_TYPE VARCHAR(40),
    BLT_DIAMETER INT,
    BLT_LENGTH INT,
    BLT_USR_ID INT,
    PRIMARY KEY (BLT_ID),
    FOREIGN KEY (BLT_USR_ID) REFERENCES WCR_USER(USR_ID)
);