CREATE DATABASE WEB1_CRUD;

USE WEB1_CRUD;

CREATE TABLE WCR_USERS (
	USR_ID INT NOT NULL AUTO_INCREMENT,
    USR_NAME VARCHAR(120) NOT NULL,
    USR_EMAIL VARCHAR(120) NOT NULL,
    USR_CPF INT NOT NULL,
    USR_PASSWD VARCHAR(20) NOT NULL,
    PRIMARY KEY(USR_ID)
);


CREATE TABLE WCR_BOLTS (
	BLT_ID INT NOT NULL AUTO_INCREMENT,
    BLT_BRAND VARCHAR(40) NOT NULL,
	BLT_TYPE VARCHAR(40) NOT NULL,
    BLT_DIAMETER INT NOT NULL,
    BLT_LENGTH INT NOT NULL,
    BLT_USR_ID INT,
    PRIMARY KEY (BLT_ID),
    FOREIGN KEY (BLT_USR_ID) REFERENCES WCR_USERS(USR_ID)
);